name: sql
channels:
  - plotly
  - conda-forge
dependencies:
  - sqlalchemy=1.4.39
  - pandas=1.4.4
  - plotly_express=0.4.1
  - numpy=1.21.5
  - scipy=1.7.3
  - sqlalchemy=1.4.39
  - libcxx=14.0.6
  - libgc=*.*