name: test
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - altair=4.2.0
  - appnope=0.1.3
  - arrow-cpp=8.0.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.5
  - boost-cpp=1.80.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - commonmark=0.9.1
  - cryptography=38.0.1
  - dataclasses=0.8
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.1.0
  - fftw=3.3.9
  - freetype=2.12.1
  - future=0.18.2
  - gflags=2.2.2
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glog=0.6.0
  - greenlet=1.1.1
  - grpc-cpp=1.46.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2021.4.0
  - ipykernel=6.16.0
  - ipython=8.5.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.85.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  # - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libnghttp2=1.47.0
  - libpng=1.6.38
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbformat=5.6.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - orc=1.7.4
  - packaging=21.3
  - pandas=1.4.4
  - parso=0.8.3
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.10.0
  - plotly_express=0.4.1
  - prompt-toolkit=3.0.31
  - protobuf=3.20.1
  - psutil=5.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=8.0.0
  - pycparser=2.21
  - pydeck=0.7.1
  - pygments=2.13.0
  - pympler=1.0.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2022.4
  - python_abi=3.10
  - pytz=2022.1
  - pytz-deprecation-shim=0.1.0.post0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2022.04.01
  - readline=8.1.2
  - requests=2.28.1
  - rich=12.6.0
  - scipy=1.9.1
  - semver=2.13.0
  - setuptools=63.4.1
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sqlalchemy=1.4.39
  - sqlite=3.39.3
  - stack_data=0.5.1
  - statsmodels=0.13.2
  - streamlit=1.13.0
  - tenacity=8.0.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.4.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - tzlocal=4.2
  - urllib3=1.26.11
  - utf8proc=2.6.1
  - validators=0.18.2
  - watchdog=2.1.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
